name: osp
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.0.1
  get_it: ^7.2.0
  flutter_map: ^0.14.0
  lottie: ^1.2.1
  material_floating_search_bar: ^0.3.6
  latlong2: ^0.8.1
  bloc: ^8.0.2
  freezed: ^1.1.1
  freezed_annotation : any
  flutter_bloc: ^8.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: any

flutter:

  uses-material-design: true
  assets:
    - assets/fire.json
    - assets/firefighter.json